name: Build and Publish
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/
            ~/.cache/pip/
            _ports-repo/
          key: always
      - name: Install Poetry
        run: pip3 install poetry
      - name: Poetry Intsall
        run: poetry install
      - name: Build the Repository
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run make -j4 prepare-repo precheck
      - name: Save the Repository
        uses: actions/upload-artifact@v3
        with:
          name: generated-repo
          path: _ports-repo/**
          if-no-files-found: error

  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feature/gh-workflow'
    runs-on: ubuntu-20.04
    environment: repo-3.bpt.pizza
    needs: [build]
    steps:
      - name: Download the Repository
        uses: actions/download-artifact@v3
        with:
          name: generated-repo
          path: repo/
      - name: Load the SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BPT_DEPLOY_KEY }}
          known_hosts: ${{ secrets.BPT_DEPLOY_HOST_KEY }}
      - name: Deploy the repository
        run: rsync -a --progress repo/. "$ENDPOINT"
        env:
          ENDPOINT: ${{ secrets.BPT_DEPLOY_TARGET }}
